config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'
  resources :packages
  resources :members do
    resources :payments do
    end
  end
  resources :registration_numbers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
    enum status: {
       active: 0,
       in_active: 1
    }
    belongs_to :package
    after_commit :date_of_ending, on: [:create]
    after_commit :change_registration_number, on: [:create, :update]
    has_many :payments, dependent: :destroy
    validates :registration_number,presence: true, uniqueness: true

    def date_of_ending
      if self.package.package_type == "annually"
        time_to_skip = 1.years
      elsif self.package.package_type == "monthly" || self.package.package_type == "personal_training_monthly"
        time_to_skip = 1.months
      elsif self.package.package_type == "quarterly" ||   self.package.package_type == "personal_training_quarterly"
        time_to_skip = 3.months
      elsif self.package.package_type == "halfyearly"
        time_to_skip = 6.months
      else
      end
      self.current_package_ending_date = self.renewal_date + time_to_skip
    end

    def change_registration_number
      if RegistrationNumber.first.reg_no == self.registration_number
         new_number = RegistrationNumber.first.reg_no + 1
         puts new_number
         RegistrationNumber.first.update(reg_no: new_number)
      end
    end
end

app/models/package.rb
class Package < ApplicationRecord
    enum package_type: {
        monthly: 0,
        quarterly: 1,
        halfyearly: 2,
        annually: 3,
        personal_training_monthly: 4,
        personal_training_quarterly: 5,
    }
    validates :price,:package_type, presence: true, uniqueness: true
    validates :price, numericality: { greater_than: 0 }
    has_many :members
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :member
end

app/models/registration_number.rb
class RegistrationNumber < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver!
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name] )
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	before_action :authenticate_user! 
	before_action :set_member, only: [:show, :edit, :update, :destroy ]

	def index
	  @members = Member.all
	end

	def new
	  @member = Member.new
	  @packages = Package.all
	end

	def create
	  @member = Member.new(member_params)
      if @member.save
        flash[:success] = 'members was successfully created.'
        redirect_to members_path
      else
        render action: :new
      end
	end

	def update
	  if @member.update_attributes(member_params)
		flash[:success] = 'members was successfully updated.'
		redirect_to members_path
	  else
		render action: :edit
	  end
	end

	def associate_package
	   @member = Member.find(params[:member_id])
	end
	
	def destroy
		@member.destroy

		respond_to do |format|
		  format.html { redirect_to members_path }
		end
	end

	def edit
	end

	private
	def member_params
	  params.require(:member).permit(:status, :address,:registration_number,:name,:phone,:email_id,:date_of_birth,:date_of_joining,:renewal_date,:package_id)
	end
	def set_member
	  @member = Member.find(params[:id])
    end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
	before_action :authenticate_user! 
	before_action :set_package, only: [:show, :edit, :update, :destroy]

	def index
	  @packages = Package.all
	end

	def new
	  @package = Package.new
	end

	def create
	  @package = Package.new(package_params)
		if @package.save
			flash[:success] = 'Package was successfully created.'
			redirect_to packages_path
		else
			render action: :new
		end	
	end

	def update
		if @package.update_attributes(package_params)
			flash[:success] = 'Package was successfully updated.'
			redirect_to packages_path
		else
			render action: :edit
		end
	end

	def destroy
	end

	def edit
	end

	private
	def package_params
	  params.require(:package).permit(:package_type, :price)		
	end
	def set_package
		@package = Package.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	before_action :authenticate_user! 
	before_action :set_member, only: [:show, :new, :edit, :update, :destroy, :create ]
	def new
   	  @payment = @member.payments.new
  	end

	def create
	  @package = @member.payments.new(payment_params)
		if @package.save
			flash[:success] = 'Payment was successfully created.'
			redirect_to @member
		else
			render action: :new
		end	
	end

	def update
		if @package.update_attributes(package_params)
			flash[:success] = 'Package was successfully updated.'
			redirect_to packages_path
		else
			render action: :edit
		end
	end

	def destroy
	end

	def edit
	end

	private
	def payment_params
	  params.require(:payment).permit(:payment_date, :payment_amount)
  	end

	def set_member
		@member = Member.find(params[:member_id])
	end

end

app/controllers/registration_numbers_controller.rb
class RegistrationNumbersController < ApplicationController
	before_action :authenticate_user!
	before_action :set_reg_no, only: [:show, :edit, :update, :destroy ]
	def new
   	  @registration_number = RegistrationNumber.new
  	end

	def create
	end

	def update
        if @reg_no.update_attributes(reg_no_params)
            flash[:success] = 'Registratio Number successfully updated.'
            redirect_to members_path
        else
            render action: :edit
        end
	end

	def destroy
	end

    def edit
      @registration_number = RegistrationNumber.first
	end

	private
	def reg_no_params
	  params.require(:registration_number).permit(:reg_no)
  	end

	def set_reg_no
	  @reg_no = RegistrationNumber.first
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def header(text)
        content_for(:header) { text.to_s }
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LNP</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Lift n Pump', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar">
         <ul class="nav navbar-nav">
            <li><%= link_to 'Home', root_path %></li>
         </ul>
         <ul class="nav navbar-nav pull-right">
           <% if user_signed_in? %>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <%= current_user.name %>
                <span class="caret"></span>
              </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
            </li>
           <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path %></li>
           <% end %>
         </ul>
        </div>
      </div>
    </nav>
   <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>
  <%= yield :top_content %>
  <div class="container">
    <h1><%= yield :header %></h1>
    <%= yield %>
  </div>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>

<%= render "devise/shared/error_messages", resource: @member %>
<div class="form-group">
  <%= f.label :status %><br />
  <%= f.select :status, Member.statuses.map{ |k,v| [k.titleize,k] },{},{ id: "member-select" } %>
</div>

  <div class="form-group">
    <%= f.label :package_id %><br />
    <%= f.select :package_id, Package.all.map{|package| [package.package_type.humanize,package.id]},{},{ id: "package-select" } %>
  </div>
  <div class="form-group">
    <%= f.label :registration_number %><br />
    <%- if f.object.registration_number == 0 %>
      <%= f.number_field :registration_number, class: 'form-control',value: RegistrationNumber.first.reg_no %>
    <%- else %>
      <%= f.number_field :registration_number, class: 'form-control',value: f.object.registration_number %>
    <%- end %>
  </div>

  <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name,required: true, class: 'form-control' %>
  </div>
 
  <div class="form-group">
      <%= f.label :phone_number %><br />
      <%= f.text_field :phone, required: true,class: 'form-control' %>
  </div>
  

  <div class="form-group">
      <%= f.label :email_id %><br />
      <%= f.email_field :email_id, required: true,class: 'form-control' %>
  </div>
  
  <div class="form-group">
      <%= f.label :date_of_birth %><br />
      <%= f.date_field :date_of_birth, required: true,class: 'form-control' %>
  </div>


  <div class="form-group">
    <%= f.label :date_of_joining %><br />
    <%= f.date_field :date_of_joining, required: true,class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %><br />
    <%= f.text_field :address, required: true,class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :renewal_date %><br />
    <%= f.date_field :renewal_date, required: true,class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Create",class: 'btn btn-primary' %>
  </div>

<% end %>
<%= javascript_include_tag 'members', 'data-turbolinks-track': 'reload' %>

app/views/members/edit.html.erb
<h3> Edit Member </h3>
<br>
<%= render 'form' %>

app/views/members/index.html.erb
    <div class="container">
      <%=link_to 'Add Member ',new_member_path,class: 'btn btn-primary pull-right' %>
      <%=link_to 'Set Registration Number ',edit_registration_number_path(RegistrationNumber.first),class: 'btn btn-primary pull-right' %>
      <h3>Current Packages</h3>
      <table id="member-table" class="table table-dark table-bordered table-striped table-responsive">
        <thead>
          <tr>
            <th> Status </th>
            <th> Name  </th>
            <th> Registration Number  </th>
            <th> Phone Number  </th>
            <th> Email  </th>
            <th> Date of Birth  </th>
            <th> Date of joining  </th>
            <th> Package Renewal Date  </th>
            <th> Package Ending Date  </th>
            <th> Current Package  </th>
            <th> Actions(s) </th>

          </tr>
        </thead>
        <tbody>
          <%- @members.each do |member|%>
          <%- if member.status == "in_active" %>
            <tr style="color: red;">
              <td><%= member.status.titleize %></td>
              <td><%=link_to member.name,member %></td>
              <td><%= member.registration_number %></td>
              <td><%= member.phone %></td>
              <td><%= member.email_id %></td>
              <td><%= member.date_of_birth %></td>
              <td><%= member.date_of_joining %></td>
              <td><%= member.renewal_date %></td>
              <td><%= member.date_of_ending %></td>
              <td><%= member.package.package_type %></td>
              <td><%=link_to 'Edit',edit_member_path(member) %> | <%=link_to 'Destroy',member_path(member), data: {:confirm => 'Are you sure?'}, :method => :delete %> </td>
            </tr>
          <%- else %>
            <tr>
              <td><%= member.status %></td>
              <td><%=link_to member.name,member %></td>
              <td><%= member.registration_number %></td>
              <td><%= member.phone %></td>
              <td><%= member.email_id %></td>
              <td><%= member.date_of_birth %></td>
              <td><%= member.date_of_joining %></td>
              <td><%= member.renewal_date %></td>
              <td><%= member.date_of_ending %></td>
              <td><%= member.package.package_type %></td>
              <td><%=link_to 'Edit',edit_member_path(member) %> | <%=link_to 'Destroy',member_path(member), data: {:confirm => 'Are you sure?'}, :method => :delete %> </td>
            </tr>
          <%-end %>
          <%-end %>
        </tbody>
      </table>
      <%= javascript_include_tag 'members', 'data-turbolinks-track': 'reload' %>
    </div>

app/views/members/new.html.erb
<h3> Add a New Member </h3>
<br>
<%= render 'form' %>

app/views/members/show.html.erb
    <div class="container">
        <%=link_to 'Add Payment ',new_member_payment_path(@member),class: 'btn btn-primary pull-right' %>
        <h3>Current Packages</h3>
        <table id="member-table" class="table table-dark table-bordered table-striped table-responsive">
          <thead>
            <tr>
              <th> Status </th>
              <th> Name  </th>
              <th> Registration Number  </th>
              <th> Phone Number  </th>
              <th> Email  </th>
              <th> Date of Birth  </th>
              <th> Date of joining  </th>
              <th> Package Renewal Date  </th>
              <th> Package Ending Date  </th>
              <th> Current Package  </th>
            </tr>
          </thead>
          <tbody>
            <tr>
            <td><%= @member.status.titleize %></td>
            <td><%= @member.name %></td>
            <td><%= @member.registration_number %></td>
            <td><%= @member.phone %></td>
            <td><%= @member.email_id %></td>
            <td><%= @member.date_of_birth.strftime("%d/%m/%Y") %></td>
            <td><%= @member.date_of_joining.strftime("%d/%m/%Y") %></td>
            <td><%= @member.renewal_date.strftime("%d/%m/%Y") %></td>
            <td><%= @member.date_of_ending.strftime("%d/%m/%Y") %></td>
            <td><%= @member.package.package_type.humanize %></td>
            </tr>
          </tbody>
        </table>
        <hr>
        <%-if @member.payments.blank? %>
            <span>No Payments to show</span>
        <%-else%>
            <table  class="table table-dark table-bordered table-striped table-responsive">
                <caption><strong>Payments</strong></caption>
                <thead>
                    <tr>
                        <td>Payment Date</td>
                        <td>Amount</td>
                    </tr>
                </thead>
                <tbody>
                    <%- @member.payments.order(:payment_date).each do |payment| %>
                        <tr>
                            <td><%=payment.payment_date.strftime("%d/%m/%Y") %></td>
                            <td><%=payment.payment_amount %></td>
                         </tr>
                    <%- end %>
-                </tbody>
            </table>
        <%-end%>
        <%= javascript_include_tag 'members', 'data-turbolinks-track': 'reload' %>
      </div>

app/views/pages/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <h1>Living In The Hall Of Fame!</h1>
      <p>Get Started.</p>
      <p>
        <%= link_to 'View Existing Members', members_path, class: 'btn btn-primary btn-lg' %>
        <%= link_to 'View Packages', packages_path, class: 'btn btn-primary btn-lg' %>
      </p>
    </div>
  </div>
<% end %>

app/views/payments/_form.html.erb
<%= form_for ([@member,@payment]) do |f| %>

  <%= render "devise/shared/error_messages", resource: @payment %>
  <div class="form-group">
    <%= f.label :payment_date %><br />
    <%= f.date_field :payment_date,class: 'form-control' ,required: true %>
  </div>

  <div class="form-group">
    <%= f.label :payment_amount %><br />
    <%= f.number_field :payment_amount,step: 0.01,class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit "Create",class: 'btn btn-primary' %>
  </div>

<% end %>
<%= javascript_include_tag 'packages', 'data-turbolinks-track': 'reload' %>

app/views/payments/edit.html.erb
<h3> Edit Payment </h3>
<br>
<%= render 'form' %>

app/views/payments/new.html.erb
<h3> Add a New Package </h3>
<br>
<%= render 'form' %>

app/views/registration_numbers/_form.html.erb
<%= form_for (@registration_number) do |f| %>

  <%= render "devise/shared/error_messages", resource: @registration_number %>
  <div class="form-group">
    <%= f.label :reg_no %><br />
    <%= f.text_field :reg_no,class: 'form-control' ,required: true %>
  </div>

  <div class="actions">
    <%= f.submit "Create",class: 'btn btn-primary' %>
  </div>

<% end %>
<%= javascript_include_tag 'packages', 'data-turbolinks-track': 'reload' %>

app/views/registration_numbers/edit.html.erb
<h3> Update Registration Number </h3>
<br>
<%= render 'form' %>